version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:latest

    steps:
      - checkout

      - restore_cache:
          key: project-cache

      - run:
          name: Prepare build
          command: make rustup

      - run:
          # NB: this GCC is (still?) broken, but should suffice for building
          # NB: needed for littlefs
          name: Install ARM gcc
          command: sudo apt-get update && sudo apt-get install gcc-arm-none-eabi libclang-dev libnewlib-dev

      - run:
          # NB: need cdefs.h for littlefs
          name: Install cdefs.h
          command: sudo apt-get update && sudo apt-get install libc6-dev

      - run:
          name: Build the firmware
          command: make build

      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
