#![no_std]
#![no_main]

extern crate panic_halt;
use cortex_m_rt::entry;

/// This is the version number generated by git.
static GIT_DESCRIBE: &'static str = env!("GIT_DESCRIBE");

#[entry]
fn main() -> ! {
    loop {}
}
